### ISSUE TITLE
端口映射的角色是否可以互换？比如反向映射端口

### ISSUE THREAD

**Issue by bhzhu203** [esrrhs/pingtunnel#1]
端口映射的角色是否可以互换？比如反向映射端口

目前功能是把client的端口映射到server

是否可以做到 把server端的端口映射到client端？

**Comment by bhzhu203** [comment]
现在已经有这样的功能了么

好像现在只能调换server和client端。   比如我这边想把server端的端口映射下来应该如何实现

**Comment by esrrhs** [comment]
你的目的是啥，现在就是local：4455和server：4455两个UDP端口通过tunnel双向通信，如果你想server访问local的另一个UDP端口比如local：4466，目前不行，没实现这个

**Comment by bhzhu203** [comment]
是的 就是想server访问local的另一个UDP端口
