### ISSUE TITLE
这个支持ipv6或者icmpv6吗？

### ISSUE THREAD

**Issue by haohetao** [esrrhs/pingtunnel#10]
如题

**Comment by esrrhs** [comment]
暂不支持，可以研究下。目前ipv4运行着也没有什么问题，不知道升级ipv6会带来什么益处？

**Comment by haohetao** [comment]
@esrrhs 
现在国内已经全面支持IPv6了，比如家用路由器上分配的IPv6就是公网的，但是IPv4都是内网的，如果在家用网络中架设pingtunnel server就只能用ipv6
再说ipv6取代ipv4也是早晚的事，对ipv6提供支持不也是响应国家号招么

**Comment by esrrhs** [comment]
@haohetao 666
