### ISSUE TITLE
关于pingtunnel几个参数的解释及使用中存在的疑惑

### ISSUE THREAD

**Issue by wansenlyt** [esrrhs/pingtunnel#12]
首先感谢作者的付出！
在使用测试过程中，有几个参数我是这样理解的：
-----------------------------------------
服务端是可以加指定端口的参数，如：
sudo ./pingtunnel -type server -l 1234
-----------------------------------------
客户端几个参数，如：
“-t  远端服务器转发的目的地址，流量将转发到这个地址”
而经过测试，若服务端指定了监听端口如上1234，则应是：-s www.yourserver.com -t www.yourserver.com:1234
表明-t后实际是指定服务端的端口(不好意思，我不懂编程；所以，意思表达不专业)。
-key 参数服务端、客户端好像仅支持数字，不支持字母；位数好像也有限制，说明里未提及。
-loglevel 参数通过命令行运行，目前查到支持info、error，未提及是否还支持其他参数。
-----------------------------------------
在使用测试过程中发现：
该工具可以直接做代理使用，但对视频流支持存在些不友好，不知道是不是因为icmp的问题。

以上是本人在使用中的一些理解，望作者可以指正一下。谢谢！

**Comment by esrrhs** [comment]
1.服务器不需要指定端口，没有监听的概念
2.转发到哪去是客户端决定的，客户端-t 1234、-t 4567都可以
3.-key -loglevel确实是没有说明很全，因为这个不是很重要的部分，文档就没搞那么详细了
4.视频流是指什么，看youtube？

**Comment by wansenlyt** [comment]
我在1.7版Centos7x64服务端设置端口后，如果客户端不指定端口，则无法联通，不知道是不是我操作有误，服务端配置如：pingtunnel -type server -l :1234 -loglevel error -key 567890。
视频流，比如youtube是有点不友好，不知道是不是我的VPS问题。
不过还是要谢谢你开发的这个工具！

**Comment by wansenlyt** [comment]
如果转发到哪去是客户端决定的，那我是否还可以这样配置：-s www.yourserver.com -t www.xxxxxx.com:1234？
我的意思就是可不可以通过第一个服务器转发到其它服务器或其它服务器的指定端口？

**Comment by esrrhs** [comment]
-t是客户端指定的 可以说本机 也可以说其他服务器

**Comment by wansenlyt** [comment]
谢谢，我再测试一下。
