### ISSUE TITLE
加速效果无法验证

### ISSUE THREAD

**Issue by jeremyxu2010** [esrrhs/pingtunnel#13]
> 测试pingtunnel的加速效果，服务器位于aws Korea，客户端位于中国大陆。
> 
> 下载centos镜像 centos mirror 直接wget、通过shadowsocks wget、通过pingtunnel wget的结果如下。
>  | wget | shaowsocks | pingtunnel
> -- | -- | -- | --
> 阿里云 | 26.6KB/s | 31.8KB/s | 897KB/s
> 移动宽带 | 23.1KB/s | 28.4KB/s | 408KB/s
> 可以看到加速效果基本上20倍。

`README`中所说的加速效果无法验证。

我这里的环境：

服务端部署在腾讯云虚拟机上（位于香港机房），带宽1M，启动命令如下：

```bash
$ echo 1 >/proc/sys/net/ipv4/icmp_echo_ignore_all
$ docker run --name pingtunnel-server -d --privileged --network host --restart=always esrrhs/pingtunnel ./pingtunnel -type server -key 123456
```

客户端在我的笔记本上，使用的广东深圳ADSL百兆带宽，启动命令如如下：

```bash
$ sudo ./pingtunnel -type client -l :1080 -s xx.xx.xx.xx -sock5 1 -key 123456 > /dev/null 2>&1
```

测速命令如下：

```bash
$ proxychains4 wget https://github.com/esrrhs/pingtunnel/files/4225497/pingtunnel_linux64.zip
```

与`shadowsocks-libev`相比，并没有看到明显的加速效果，反而速度有很大幅度降低。`shadowsocks-libev`可以使下载速度达到`100KB/s`，而`pingtunnel`只能使下载速度达到`55KB/s`，基本是打骨折，而且还使`wget`时常断开重连。

**Comment by esrrhs** [comment]
@jeremyxu2010 感谢反馈，你的问题是带宽只有1M，并且ss的速度已经跑满带宽。这种没必要用这个了，因为再怎么跑也不会超过带宽。如果你的服务器带宽10M，但是ss的速度比如只有100k，那么可以试试看。
原因是因为这个类似于可靠udp的方式，会有流量损耗，在网络好的情况比如局域网下，是肯定不如tcp的。
