### ISSUE TITLE
pingtunnel有一定几率会发生丢包现象

### ISSUE THREAD

**Issue by bhzhu203** [esrrhs/pingtunnel#14]
![2020-02-23 11-08-57 创建的截图1](https://user-images.githubusercontent.com/3523160/75103007-b64a5d80-562f-11ea-9fe3-214bd6c57f51.jpg)

pingtunnel有一定几率会发生丢包现象，个人使用的感觉是30%左右。

1.使用pingtunnel浏览网页（github等），特别是https类型的网页会比较容易出现  “conect_reset"的错误
2.使用pingtunnel下载大文件时，大概率会出现连接断掉的现象

感觉pingtunnel传输过程中把没有维护用户的数据，没有重传机制，丢包了

客户端：./pingtunnel -type client -l :4455 -s xxxx.com -sock5 1  -key 7756
服务端：./pingtunnel -type server -key 7756 -maxconn 10 -maxprt 10 -maxprb 30 -nolog 1
版本2019-12-29  左右的版本

是pingtunnel的功能问题 还是服务端的配置问题？服务器是openvz的，内存较小，所以服务端参数调小了 不知道是否有影响  谢谢

**Comment by esrrhs** [comment]
1.pingtunnel底层会做重传的，不然tcp转发根本没法用
2.你的问题应该是 -maxconn 10导致的，超过了就会被关掉，所以有你截图这种。因为现在浏览器为了加速会一下子发多个tcp链接出去
3.内存应该不是问题，设置大点虚拟内存。我的server 512M的内存都是按照默认配置跑的

**Comment by bhzhu203** [comment]
现在去掉 -maxconn 10 不会发生浏览网页中断的现象了
但是下载大文件   比如github的git大文件会出现下载中断的现象  几乎没有成功过  是因为 -maxprt 10 -maxprb 30 这些参数导致的么

还有pingtunnel的服务端占用内存偏高（70～80M） 客户端是20M  是因为缓存太多的缘故么 谢谢

**Comment by esrrhs** [comment]
@bhzhu203 恩，下载中断的问题是个bug，你下载最新版试试。内存占用的话，可能是buffersize和windowsize的设置导致的，另外70m很小了吧？

**Comment by zhezhe168** [comment]
同上，我这边也有下载中断的现象，断断续续

**Comment by esrrhs** [comment]
@zhezhe168 下载最新版再试试
