### ISSUE TITLE
[question] 怎么才能用TCP转发ws+tls流量

### ISSUE THREAD

**Issue by xianren78** [esrrhs/pingtunnel#16]
./pingtunnel -type client -l localip:4455 -s mydomain.com -t  mydomain.com:443 -tcp 1 -key pass
使用方法如上，ping pong正常，把v2ray的服务器和端口改成localip:4455; 测试失败，手动访问https://localip:4455 提示ERR_SSL_PROTOCOL_ERROR
另外，上述方法转发非tls流量没问题。

**Comment by esrrhs** [comment]
恩，tls有验证安全性啥的吧，这种方式可能行不通，试试socks5代理看看

**Comment by xianren78** [comment]
> 恩，tls有验证安全性啥的吧，这种方式可能行不通，试试socks5代理看看

好的，谢谢。
