### ISSUE TITLE
浏览器无法访问网站

### ISSUE THREAD

**Issue by Expost** [esrrhs/pingtunnel#19]
首先很感谢作者开发这个工具，但是我这边按照说明配置好后，浏览器无法打开网站。客户端使用的qt，配置如下：
![image](https://user-images.githubusercontent.com/7315086/80823920-0cc7af80-8c10-11ea-9d2c-92e064b070dc.png)

浏览器为chrome，使用switchyomega插件，配置如下：
![image](https://user-images.githubusercontent.com/7315086/80824031-3b458a80-8c10-11ea-8ca6-b0f5caf8439c.png)

服务器为腾讯云ubuntu，执行的命令为sudo ./pingtunnel -type server。使用浏览器打开网页时，能从log中看到有数据包发送和接收，但网页就是打不开。求教是我哪里配置有问题吗？

**Comment by esrrhs** [comment]
@Expost dns的问题，在浏览器上勾选上dns走socks代理

**Comment by Expost** [comment]
感谢作者回复。

我今天用我国内的服务器又测试了下，用法应该没问题，代理后可以正常访问国内网站，但换到腾讯云香港服务器上就是不行，国内网站都没办法访问。感觉像是服务器的问题，我暂时还是先用其他的软件吧，等以后换其他服务器了再试试。

**Comment by esrrhs** [comment]
@Expost 对，腾讯云好像对ping做限制了，阿里云还没问题

**Comment by esrrhs** [comment]
@Expost 腾讯云默认关闭ping了，echo "0" >/proc/sys/net/ipv4/icmp_echo_ignore_all

**Comment by Expost** [comment]
这个配置我之前有调整过，最开始我是用qt工具连接后，显示ping fail，但我用ping命令是可以ping通的，后来看说明中提到这个可选配置，我就把它改为1了，改为1之后，qt工具不再显示ping fail，而是正常的时间。

我刚又把配置改为0后，qt工具就又显示ping fail了。不过虽然显示ping fail，但从服务器的log来看是可以收到我要访问的域名信息的，应该是ok的。

不过无论我改为0还是1，都无法访问网页😥。不知道是服务器哪的问题，因为开的服务比较多，我也不想重启，我抽空换台其他国外服务器试试吧。
