### ISSUE TITLE
请问Windows上启动了，怎么才能使用？小白一个，没有详细说明不会

### ISSUE THREAD

**Issue by bzvs1992** [esrrhs/pingtunnel#2]
![image](https://user-images.githubusercontent.com/6036446/50754769-c4a1b280-1291-11e9-8a0b-2c651dbf4784.png)
![image](https://user-images.githubusercontent.com/6036446/50754808-e7cc6200-1291-11e9-9b37-ebc427fbd40c.png)
但是怎么UDP代理怎么处理？

**Comment by esrrhs** [comment]
github找个kcptun（把tcp转成udp），对于你的配置，server：./server_linux_amd64 -t "TARGET_IP:8388" -l ":4455" -mode fast2，client：./client_darwin_amd64 -r "127.0.0.1:4455" -l ":8388" -mode fast2，这样就把客户端的8388端口的tcp连接转到了服务器的8388端口

**Comment by luckypoem** [comment]
@esrrhs 
如果不搭配kcptun，可以直接利用pingtunnel翻#墙吗

**Comment by esrrhs** [comment]
@luckypoem 目前不行，因为为了实现简单，转发的是udp包。不过后面准备支持tcp包转发。

**Comment by luckypoem** [comment]
在支持tcp包转发后，麻烦通知一声。谢谢！
我发现用来做dns proxy不错：
sudo pingtunnel-by-esrrhs -type client -l :53 -s my-vps-ip -t 8.8.8.8:53
这样，可以解决dns污染问题

**Comment by esrrhs** [comment]
@luckypoem 已经可以tcp转发了

**Comment by briteming** [comment]
@esrrhs 
可以提供mac上的可执行文件吗？我build失败

**Comment by esrrhs** [comment]
@briteming 加上了 https://github.com/esrrhs/pingtunnel/releases/tag/1.3
