### ISSUE TITLE
不知道怎么用

### ISSUE THREAD

**Issue by chmis8000** [esrrhs/pingtunnel#21]
比如，我电脑， 公网服务器
两个之间想用ICMP包，我电脑 的指定程序，访问本机的指定端口，可以访问 公网服务器 的指定TCP 端口。
如何操作？

**Comment by esrrhs** [comment]
@chmis8000 pingtunnel.exe -type client -l :4455 -s www.yourserver.com -t www.yourserver.com:4455 -tcp 1 这个就是把你电脑的4455的流量转发到www.yourserver.com:4455的端口上去，相当于你连本机的4455就相当于连的是www.yourserver.com:4455

**Comment by chmis8000** [comment]
我测试并不通:
服务器：win2008r2 x64： 
  pingtunnel.exe -type server
我电脑: win8.1 x64:
  pingtunnel.exe -type client -l :5678 -s 123.207.143.xx -t 123.207.143.xx:3380 -tcp 1

而用传统的 proxy-go 项目（ https://snail007.github.io/goproxy/manual/zh/#/ ），tcp代理的 二级代理模式，测试是没问题的。
麻烦，我哪里配置得不对么？

**Comment by esrrhs** [comment]
@chmis8000 哦哦，windows的server吗？关掉防火墙，用管理员启动试试。client看到有pong from xxxx的日志吗？

**Comment by chmis8000** [comment]
你有测试过 server 和 client 就是windows的情况吗？ 我局域网测试，两边都是win8.1， 两台机子都关闭了windows的防火墙，

这是client端可以访问的server端的web地址：
http://192.168.0.30:6603/

这是server端运行的命令：
pingtunnel.exe -type server

这是client端运行的命令：
pingtunnel.exe -type client -l :5678 -s 192.168.0.30 -t 192.168.0.30:6603 -tcp 1

这是client端测试web：不通：
http://127.0.0.1:5678/

麻烦确认，这个支持windows吗？

**Comment by chmis8000** [comment]
翻阅以前close的说默认不支持http， 但我server端装了一个 sql server数据库，端口7789
在client端，直接访问server端的7789是可以正常的。
但，用映射的 5678 仍旧连接不上数据库。

**Comment by esrrhs** [comment]
@chmis8000 恩 根据之前的反馈，server不支持跑在windows上面，这个回头有时间查查，先用linux跑server吧

**Comment by chmis8000** [comment]
哦，手头没linux服务器

**Comment by chmis8000** [comment]
最近买了linux服务器，测试通了， client是win，server是centos（参数-s），目标是win（参数 -t）, server和目标在同一个虚拟内网里面，所以目标虽然有外网IP，仍旧用内网IP，避免走流量。
供大家参考（IP变换过，不要直接试）：
pingtunnel.exe -type client -l :7733 -s 130.83.212.171 -t 10.140.10.201:3308 -tcp 1 -tcp_gz 150 -key 951 -noprint 1
