### ISSUE TITLE
server端到client端反向请求失败

### ISSUE THREAD

**Issue by uxsi** [esrrhs/pingtunnel#23]
从client到server是正常的，从server到client失败了。

在server端设置`ALL_PROXY=socks5://127.0.0.1:4455`，curl url的时候提示拒绝，是哪里设置有问题吗？

* About to connect() to proxy 127.0.0.1 port 4455 (#0)
*   Trying 127.0.0.1...
* Connection refused
* Failed connect to 127.0.0.1:4455; Connection refused
* Closing connection 0
curl: (7) Failed connect to 127.0.0.1:4455; Connection refused

**Comment by esrrhs** [comment]
@uxsi 不支持方向操作啊
