### ISSUE TITLE
Removing Crazy Big Files GeoLite2-Country.mmdb

### ISSUE THREAD

**Issue by cxjava** [esrrhs/pingtunnel#24]
能不能用 [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/ )移除git里面比较大的文件，比如GeoLite2-Country.mmdb, GeoLite2-City.mmdb

我克隆整个项目时，发现有31MB。

<img width="492" alt="WechatIMG409" src="https://user-images.githubusercontent.com/802316/81703034-a90a7580-949e-11ea-9411-9e5243a0ea9b.png">

我自己移除之后变小了很多。

<img width="515" alt="WechatIMG410" src="https://user-images.githubusercontent.com/802316/81703778-9e041500-949f-11ea-8a6d-7017af179e52.png">

参考shell，也可以参考上面链接，我是移除大小超过1MB的历史提交文件

```shell
git clone --mirror git@github.com:cxjava/pingtunnel.git

java -jar ~/bfg-1.13.0.jar --strip-blobs-bigger-than 1M pingtunnel.git

cd pingtunnel.git

git reflog expire --expire=now --all && git gc --prune=now --aggressive

git push

```

**Comment by cxjava** [comment]
关联 esrrhs/go-engine#1

**Comment by esrrhs** [comment]
@cxjava 我用go-engine试了下 对于clone好像没效果？另外这个30M很小了吧

**Comment by cxjava** [comment]
@esrrhs 是的，clone没有效果，需要加参数`--mirror`, 30M克隆很慢了。

你那个 go-engine 更没法弄。。。昨晚用 `go get -u ` 已经下载了100M了，才显示下载了10%，估计得有7，8百兆大。。。

个人建议go-engine那个工程还是分离一下，最好不要用src目录去存放吧。

想提个pr都没缘分。。。

**Comment by esrrhs** [comment]
@cxjava 是的，挺大。。建议挂个代理，正好可以先使用下pingtunnel

**Comment by cxjava** [comment]
@esrrhs 代理是必备的

有没有打算改进下这个依赖？

**Comment by esrrhs** [comment]
@cxjava 没有，懒得改了。依赖的挺多的其实
