### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by steom** [esrrhs/pingtunnel#27]
on windows with 32 and 64 bit binaries

pingtunnel.exe -type server

pingtunnel.exe -type client -l 127.0.0.1:3388 -s xx.xx.xx.xx -t xx.xx.xx.xx:3389 -tcp 1

=== END goroutine stack dump ===
←[0;00m←[38;5;46m[INFO] [2020-06-08T19:27:35.310891+02:00] [/root/go/src/github.
com/esrrhs/go-engine/src/pingtunnel/server.go:140] [github.com/esrrhs/go-engine/
src/pingtunnel.(*Server).processPacket] ping from xx.xx.xx.xx 2020-06-08 19:27:27
.1503909 +0200 CEST -1 11169 3
←[0;00mpanic: runtime error: invalid memory address or nil pointer dereference [
recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x45f7c0]

github.com/esrrhs/go-engine/src/common.CrashLog()
        /root/go/src/github.com/esrrhs/go-engine/src/common/error.go:24 +0x1d1
panic(0x7a26e0, 0xb26228)
        /usr/local/go/src/runtime/panic.go:967 +0x119
github.com/esrrhs/go-engine/src/pingtunnel.(*Server).processDataPacket(0x12c4009
0, 0x12c040b0)
        /root/go/src/github.com/esrrhs/go-engine/src/pingtunnel/server.go:266 +0
x20c
github.com/esrrhs/go-engine/src/pingtunnel.NewServer.func1(0x765c40, 0x12c040b0)

        /root/go/src/github.com/esrrhs/go-engine/src/pingtunnel/server.go:28 +0x
36
github.com/esrrhs/go-engine/src/threadpool.(*ThreadPool).run(0x12e94000, 0x46)
        /root/go/src/github.com/esrrhs/go-engine/src/threadpool/threadpool.go:78
 +0x11c
created by github.com/esrrhs/go-engine/src/threadpool.NewThreadPool
        /root/go/src/github.com/esrrhs/go-engine/src/threadpool/threadpool.go:39
 +0x1d2

**Comment by esrrhs** [comment]
the server does not support running on windows, use linux instead
