### ISSUE TITLE
对文档有疑惑，麻烦解答一下

### ISSUE THREAD

**Issue by jackyxie** [esrrhs/pingtunnel#28]
文档下面这部分不太理解怎么搭配使用？目前我直接用pingtunnel 做客户端和服务器端。

```
建议套用其他协议使用，如ss client->pingtunnel client->pingtunnel server->ss server
```

pingtunnel server 怎么转发到  ss server呢？求指导

**Comment by esrrhs** [comment]
@jackyxie 是pingtunnel client指定的，-t参数

**Comment by jackyxie** [comment]
> @jackyxie 是pingtunnel client指定的，-t参数

pingtunnel server 怎么转发给 ss server呢？

**Comment by jackyxie** [comment]
> @jackyxie 看文档，pingtunnel server不需要指定参数

那这个架构怎么实现呢?
pingtunnel client  到  pingtunnel server这部分我现在已经在用了.   怎么把pingtunnel server的流量再转发到 ss server呢?

**Comment by jackyxie** [comment]
另外发现一个问题,我在同一台主机上启动客户端和服务端是不是会崩溃的?

**Comment by esrrhs** [comment]
@jackyxie 你还是没理解。你把你的使用命令和ss server的地址贴出来才能给你讲明白
