### ISSUE TITLE
关于pingtunnel对内容加密的范围

### ISSUE THREAD

**Issue by zhltristan** [esrrhs/pingtunnel#32]
作为使用者，在使用pingtunnel的过程中，通过wireshark抓包发现了一些未被加密的数据，想请教一下作者是出于什么样的考虑，或者是我在理解该工具使用上有什么误会，谢谢大大！
1、客户端 pingtunnel.exe -type client -sock5 1 -l 127.0.0.1:4455 -s [myserverip] -t 127.0.0.1:4455 -key [mykey]，浏览器直接使用该socks5代理，可以看到发往服务端的包中，实际访问的域名和端口未被加密
![image](https://user-images.githubusercontent.com/50695187/85935173-496a0b80-b920-11ea-8fcb-1c4bb857787e.png)
2、套上一层shadowsocks，客户端pingtunnel.exe -type client -tcp 1 -l 127.0.0.1:4455 -s [myserverip] -t 127.0.0.1:20002 -key [mykey]，shadowsocks client指向本地4455端口，shadowsocks server监听20002端口，抓包发现，发往服务端的包中，-t的部分未被加密，
![image](https://user-images.githubusercontent.com/50695187/85935261-52a7a800-b921-11ea-951c-ee8244692d45.png)

**Comment by zhltristan** [comment]
ps：服务端和客户端都是最新2.3版本

**Comment by esrrhs** [comment]
@zhltristan 没有做加密，底层只是protobuff的打包而已
