### ISSUE TITLE
NAT环境中无法连接

### ISSUE THREAD

**Issue by wilsonleeee** [esrrhs/pingtunnel#38]

**Comment by esrrhs** [comment]
server端在NAT环境？

**Comment by wilsonleeee** [comment]
客户端在NAT环境




wilson_lee
773560195@qq.com




------------------ 原始邮件 ------------------
发件人: zhao xin <notifications@github.com&gt;
发送时间: 2020年7月15日 12:29
收件人: esrrhs/pingtunnel <pingtunnel@noreply.github.com&gt;
抄送: huahuahuahua <773560195@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[esrrhs/pingtunnel] NAT环境中无法连接 (#38)





 
server端在NAT环境？

**Comment by esrrhs** [comment]
能ping就可以用，用不了的话，和nat没关系，和网络环境的ping处理有关

**Comment by wilsonleeee** [comment]
现在NAT连不上，虚拟机失败了


wilson_lee
773560195@qq.com




------------------ 原始邮件 ------------------
发件人: zhao xin <notifications@github.com&gt;
发送时间: 2020年7月15日 14:24
收件人: esrrhs/pingtunnel <pingtunnel@noreply.github.com&gt;
抄送: huahuahuahua <773560195@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[esrrhs/pingtunnel] NAT环境中无法连接 (#38)





 
能ping就可以用，用不了的话，和nat没关系，和网络环境的ping处理有关

**Comment by esrrhs** [comment]
为什么要在虚拟机中跑？

**Comment by B0y1n4o4** [comment]
状态防火墙和 NAT
那么就出现了一个问题，隧道如何穿过状态防火墙或 NAT？一些设备会过滤没有匹配响应数据包的 Ping 包。而在非对称连接中，来自服务器端的流量会大于客户端，反之亦然，这样客户端可能会丢弃一些相应数据包，因为响应数据包多余请求数据包。

icmptunnel 有一个机制来专门解决这个问题。客户端会定期发送一个空的 ICMP 请求数据包给状态防火墙或 NAT，而这些请求数据包都会被记录在防火墙状态表中。同时通过保持发送带有载体的数据包，这样客户端会维持一个可以用于服务器端发送数据的“数据包窗口”。

[文字引用](https://www.cnblogs.com/bonelee/p/7462218.html)

[ICMPTunnel fix NAT compatibility push](https://github.com/lnslbrty/ptunnel-ng/pull/7/commits/bb064bb52a6405116e53d33853fc254f0cb6398d)

因为客户端在目标网络下存在NAT的情况，虚拟机模拟NAT网络，本地测试偶尔存在一些数据包可以通过NAT出来，大部分数据包并没有 @esrrhs 

还望作者闲暇时方便修复下，感谢🙏

**Comment by esrrhs** [comment]
这种网络我接触过，以前加过这种机制，定时发空ping，但是效果甚微，其实运营商还对ping限频了。所以这种网络就不需要用pingtunnel了，速度很慢，意义不大，不如直接TCP
