### ISSUE TITLE
公司网络能使用，在家里的网络不能使用

### ISSUE THREAD

**Issue by lijc210** [esrrhs/pingtunnel#39]
如果是运营商对icmp限制的原因导致，有什么检测方法验证吗

**Comment by esrrhs** [comment]
恩。。首先看看client的ping pong的日志是否正常吧，不正常肯定就没法用。有的网络就算正常，速度也很慢，因为运营商限制的问题

**Comment by lijc210** [comment]
买的是国外的服务器，家里网络能ping通，看日志传输都是0kb，在公司能正常使用，这种情况在家里使用是不是无解

**Comment by esrrhs** [comment]
无解，换个运营商试试。或者用其他节点中转下
