### ISSUE TITLE
客户端监听成功，怎么使用

### ISSUE THREAD

**Issue by qiufeihai** [esrrhs/pingtunnel#4]
客户端监听成功，怎么使用，是需要其他软件配合用吗，可以fq的不

**Comment by esrrhs** [comment]
server也要启动

**Comment by qiufeihai** [comment]
都启动之后，怎么流量走客户端端口

**Comment by esrrhs** [comment]
客户端开启sock5 监听比如1080端口 剩下的事情就是把浏览器的代理设置到1080端口

**Comment by qiufeihai** [comment]
那tcp或者udp模式呢，安全性如何，会不会被封ip之类的

**Comment by esrrhs** [comment]
这个tcp udp指的是本地的连接方式，中间的路径是走的ping的icmp协议。你看下readme那张图。至于安不安全，都不好说

**Comment by qiufeihai** [comment]
手机上具体怎么使用

**Comment by esrrhs** [comment]
@qiufeihai pc的搞定了吗？手机上需要对应的客户端，这块是我的技术盲区了

**Comment by qiufeihai** [comment]
pc的可以了，现在手机只能通过电脑的ip:port来连

**Comment by esrrhs** [comment]
@qiufeihai 得等出手机客户端才行
