### ISSUE TITLE
映射nginx端口做http下载文件损坏问题

### ISSUE THREAD

**Issue by ffxisf** [esrrhs/pingtunnel#40]
最近在国外VPS上安装pingtunnel后，客户端映射VPS的nginx服务端口，做下载发现总出错，不是下载中断就是下载完成压缩包损坏，不知道哪里被干扰了，下载很不稳定，经常中断

**Comment by esrrhs** [comment]
> 
> 
> 最近在国外VPS上安装pingtunnel后，客户端映射VPS的nginx服务端口，做下载发现总出错，不是下载中断就是下载完成压缩包损坏，不知道哪里被干扰了，下载很不稳定，经常中断

是不是文件快结束的时候，失败了。这是个已知的问题，近期修复下。

**Comment by esrrhs** [comment]
@ffxisf 试试2.4的新版本 有没有改善

**Comment by ffxisf** [comment]
问题没有解决与改善，下载还是中断

**Comment by esrrhs** [comment]
那估计是网络的问题了，大流量icmp会被断流
