### ISSUE TITLE
check connection or tunnel with commnad  ? help please

### ISSUE THREAD

**Issue by ingnelson** [esrrhs/pingtunnel#42]
Hello @esrrhs @honwen 

what is the commnad to check if the tunnel is stablished ? can you give me the commnad please ? using CURL ? please
i want to visit www.google.com through the tunnel.
Do I have to use Tmux and curl ? Can you give the command , please . I am a newbie.

i install pingtunnel on my ubuntu VPS .
I run the binary  linux64 server  using : `sudo ./pingtunnel -type server`

![image](https://user-images.githubusercontent.com/6626845/92294087-f7c49b00-eee5-11ea-8d4e-7f317f6eebd6.png)

i download the binary file for arm64 for my android phone and i run it inside TEMUX app ( linux terminal) : 

`./pingtunnel -type client -l :4455 -s 172.245.22.211 -t 172.245.22.211:4455 -tcp 1`

![Screenshot_2020-09-04-19-40-00-627_com termux](https://user-images.githubusercontent.com/6626845/92294205-2c852200-eee7-11ea-9281-5306922ce01f.jpg)

i will wait your reply, because I really need it and I want to test pingtunnel

**Comment by esrrhs** [comment]
the client log "pong from 172.245.22.211" means the tunnel is ok,  but there is no android app for pingtunnel,  so you can't use it to visit google.com,  maybe someone can build a pingtunnel android client, just like shadowsocks. 
in android, you can use shadowsocks,  and if the speed is too slow, you can try pingtunnel like this:  shadowsocks android client---->pingtunnel client---->pingtunnel server---->shadowsocks server

**Comment by ingnelson** [comment]
@esrrhs if the client received "pong" mean the Connection is stablished .
The client is listening on localhost (1027.0.0.1) port 1080 ?
 So if I a new terminar on client and use this next command.
`curl -x http://127.0.0.1:1080/ http://www.google.com/`

 can I visit www.google.com ?

**Comment by esrrhs** [comment]
start pingtunnel client use command like this: 
./pingtunnel -type client -l :1080 -s 172.245.22.211 -sock5 1  
then:
curl --socks5 127.0.0.1:1080 google.com 
it will show result, and then you can use any proxy app that support socks5 proto to browse website, the socks5 address is 127.0.0.1:1080
