### ISSUE TITLE
请问pingtunnel服务器端使用的端口是哪个

### ISSUE THREAD

**Issue by Im-fengyin** [esrrhs/pingtunnel#43]
服务器设置好后可以ping通ip，但win端设置完成后ping fail。测试了服务器打开全部端口，本地关闭防火墙，还是不可以。。。

**Comment by esrrhs** [comment]
server是icmp的，没有端口的概念。你看看windows client有没有用管理员权限启动

**Comment by Im-fengyin** [comment]
> server是icmp的，没有端口的概念。你看看windows client有没有用管理员权限启动

[INFO] [2020-09-14T10:08:40.538456264+08:00] [server.go:140] [github.com/esrrhs/go-engine/src/pingtunnel.(*Server).processPacket] ping from xxx.xxx.xxx.xxx（手工打码） 2020-09-14 10:08:39.6573392 +0800 CST 0 8648 18447
[INFO] [2020-09-14T10:08:40.591012998+08:00] [server.go:553] [github.com/esrrhs/go-engine/src/pingtunnel.(*Server).showNet] send 0Packet/s 0KB/s recv 0Packet/s 0KB/s 0Connections

服务器端可以接到本机的ping，但是连接不上，请问可能有什么问题？

**Comment by esrrhs** [comment]
先看看key有没有对上，然后在其他机器上试试client行不行。有可能是你的网络问题
