### ISSUE TITLE
可以于服务器对接上，但不能接受包 ，可以发包

### ISSUE THREAD

**Issue by 13762506707** [esrrhs/pingtunnel#44]
<img width="744" alt="1" src="https://user-images.githubusercontent.com/31812150/93278589-b2627080-f7f7-11ea-950e-8cc2de395864.png">

**Comment by 13762506707** [comment]
pingtunnel -type client -l 127.0.0.1:1080 -s 8.129.75.138 -t 8.129.75.138:4455 -tcp 1

**Comment by 13762506707** [comment]
pingtunnel -type client -l 127.0.0.1:1080 -s myServerIp -t myServerIp:4455 -tcp 1

**Comment by esrrhs** [comment]
没有ping pong的日志在打印吧

**Comment by 13762506707** [comment]
连接校园网，用"pingtunnel -type client -l 127.0.0.1:1080 -s serverIp -sock5 1 " 就只有ping.
但用“pingtunnel -type client -l 127.0.0.1:1080 -s serverIp  -t serverIp :4455 -tcp 1” 就有pong.

**Comment by esrrhs** [comment]
client端的日志得有pong才能正常工作

**Comment by 13762506707** [comment]
手机放网络的时候可以pong，但连接校园网时没验证就没有pong

**Comment by 13762506707** [comment]
这个有解决方案吗？^_^

**Comment by 13762506707** [comment]
tcp 和 udp 不验证也可以pong ，可以用" pingtunnel -type client -l 127.0.0.1:1080 -s serveIp -t serveIp:4455 -tcp 1  "吗？

**Comment by esrrhs** [comment]
> 
> 
> tcp 和 udp 不验证也可以pong ，可以用" pingtunnel -type client -l 127.0.0.1:1080 -s serveIp -t serveIp:4455 -tcp 1 "吗？

可以，你需要在server上再启动一个[socksserver](https://github.com/esrrhs/socksserver)，本地1080就可以socks5的协议访问了
