### ISSUE TITLE
访问谷歌证书错误，其他网站没问题

### ISSUE THREAD

**Issue by jiqing112** [esrrhs/pingtunnel#47]
今天突然出现的，不太清楚是不是我的网络问题。

访问谷歌时候浏览器报错证书错误，其它网站youtube Twitter 之类没问题

![Snipaste_2020-11-09_14-45-42](https://user-images.githubusercontent.com/17674011/98508549-8bed0e80-2257-11eb-96e6-195521255684.png)
![Snipaste_2020-11-09_14-48-37](https://user-images.githubusercontent.com/17674011/98508677-cce52300-2257-11eb-949b-312a613a7b21.png)
![Snipaste_2020-11-09_14-48-48](https://user-images.githubusercontent.com/17674011/98508681-ce165000-2257-11eb-9340-63865dad26a1.png)
![Snipaste_2020-11-09_14-48-55](https://user-images.githubusercontent.com/17674011/98508684-ceaee680-2257-11eb-8648-0c1a6d7dc2b0.png)

**Comment by jiqing112** [comment]
![image](https://user-images.githubusercontent.com/17674011/98509055-79bfa000-2258-11eb-8429-98f97d75a94a.png)

**Comment by jiqing112** [comment]
![image](https://user-images.githubusercontent.com/17674011/98509133-978d0500-2258-11eb-831e-38923c7d618a.png)

**Comment by rampageX** [comment]
去 证书管理器 里面删掉这个自签证书

**Comment by esrrhs** [comment]
试试楼上兄弟的，我没遇到过
