### ISSUE TITLE
tcp 转发和udp转发的使用举例

### ISSUE THREAD

**Issue by drunkpig** [esrrhs/pingtunnel#50]
kcptun的server 转向固定的一个 ip:port, 这样 ip:port再对流量进行转发。
pingtunnel  server是自动集成了转发功能吗

**Comment by esrrhs** [comment]
是的，pingtunnel server转发到哪是由client指定的

**Comment by drunkpig** [comment]
转发s5我能理解，但是转发tpc, udp是怎么用呢，应用层应该怎么设置？

**Comment by esrrhs** [comment]
ss client->pingtunnel client->pingtunnel server->ss server

**Comment by drunkpig** [comment]
> ss client->pingtunnel client->pingtunnel server->ss server

我是对比kcptunnel来理解的，这里面产生了疑问：
普通ss:
ss-cli{data:<dist_ip, dist_port>....}[ss-server-ip,ss-server-port]   --------> ss-server{解密dist_ip,dist_port}   ------------> dist_ip-server

使用kcp之后：
ss-cli{data:<dist_ip, dist_port>....}[kcptun-cli-ip,ss-server-port]    ------- kcptun-server  ----> 转发到ss-server-ip
上述从kcptun-server转发到ss-server-ip利用了Kcptun-server 里的一个 `-t ip` 参数， kcptun-server总是吧收到的包转发到一个固定的ip, 例如ss-server或者 socks5代理ip。

然而我并没有看到从pingtunnel-server ---->  ss server这一步的设置参数是什么。  pingtunnel-server是如何知道这个包要转向哪里？比如我要把数据包转发到server本地一个  127.0.0.1:8888 的socks5代理上出去，哪个参数可以设置

**Comment by drunkpig** [comment]
刚又看了下ICMP协议，
pingtunnel.exe -type client -l :4455 -s www.yourserver.com -t www.yourserver.com:4455 -tcp 1

这条命令的意思是发送到本地4455端口上的流量都会被转发到  yourserver.com 的4455上！因为ICMP没有端口号。

我理解了，这样就达到了客户端设置转发target的问题。

**Comment by esrrhs** [comment]
> 
> 
> 刚又看了下ICMP协议，
> pingtunnel.exe -type client -l :4455 -s [www.yourserver.com](http://www.yourserver.com) -t [www.yourserver.com:4455](http://www.yourserver.com:4455) -tcp 1
> 
> 这条命令的意思是发送到本地4455端口上的流量都会被转发到 yourserver.com 的4455上！因为ICMP没有端口号。
> 
> 我理解了，这样就达到了客户端设置转发target的问题。

是的

**Comment by drunkpig** [comment]
实测下来用来FQ，看youtube, kcptun速度12700，换pingtunnel 只有700。作者在首页对比的kcp是什么场景啊，难道不是FQ吗？
![kcp](https://user-images.githubusercontent.com/60862764/103460275-e7b3af80-4d4f-11eb-8c3d-4d48289e8db7.png)

**Comment by drunkpig** [comment]
我理解是这个icmptunnel对丢包的处理没有kcp那样考虑那么多，所以在丢包不大的情况下可以用？例如国内的互联

**Comment by esrrhs** [comment]
> 
> 
> 我理解是这个icmptunnel对丢包的处理没有kcp那样考虑那么多，所以在丢包不大的情况下可以用？例如国内的互联

丢包越大的情况下越适合用pingtunnel，你刚才的场景可以试试tcp的速度有多少呢？我测试的环境是阿里云连到搬瓦工，这个和具体的网络环境有关系，以及tcp、udp、icmp走的路线有关。可以都测试一下，哪个快用哪个，不一定是绝对的
