### ISSUE TITLE
关于tcp的选项意义是什么？

### ISSUE THREAD

**Issue by lxjsailor** [esrrhs/pingtunnel#8]
我有一个问题想请教下。
工具中有一些关于tcp的选项，例如设置窗口、缓冲区等等，这些选项的意义在哪里？
通常来讲，这些和性能有关，应该是越大越好，为什么需要用户来调节他？
谢谢。

**Comment by esrrhs** [comment]
方便用户定制化，也有默认值。越大影响内存也越大，可能有的人是想在路由器里跑呢？
