### ISSUE TITLE
socks version not supported

### ISSUE THREAD

**Issue by tianxia0079** [esrrhs/pingtunnel#9]
[ERROR] [2020-02-20T15:24:06.0053699+08:00] [/root/go/src/github.com/esrrhs/go-engine/src/pingtunnel/client.go:714] [github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptSock5Conn] socks handshake: socks version not supported

这个报错有影响吗

**Comment by tianxia0079** [comment]
pc上的浏览器通过代理链接到客户端，刷新网页，就报错这个，请问怎么解决

**Comment by esrrhs** [comment]
@tianxia0079 浏览器要用sock5代理方式

**Comment by tianxia0079** [comment]
@esrrhs 
我这样操作的，帮忙看下是否对：
第一步：启动服务端
title=服务端
pingtunnel.exe -type server

第二步：启动客户端
![image](https://user-images.githubusercontent.com/50256566/74918383-f6c59380-5403-11ea-8c43-af22f1fa9187.png)

第三步：另外一台电脑用360极速浏览器设置代理
![image](https://user-images.githubusercontent.com/50256566/74918517-2aa0b900-5404-11ea-9246-2d8696101cd8.png)
然后随便访问个网址。异常了。
错误日志：
```
 socks handshake: socks version not supported
```
第三步不可以用，请问那一步有问题啊？谢谢了

**Comment by esrrhs** [comment]
@tianxia0079 别用360，他这个不是socks5代理，试试firefox

**Comment by tianxia0079** [comment]
![image](https://user-images.githubusercontent.com/50256566/74919514-acddad00-5405-11ea-95a4-570c01a74c0c.png)
通过socke链接测试，可以发包，但就是不返回包，好奇怪

**Comment by tianxia0079** [comment]
> @tianxia0079 别用360，他这个不是socks5代理，试试firefox

Proxifier 我现在换成Proxifier了，专门连接socket的。现象是客户端，只接受包，不返回包，大概什么原因啊

**Comment by esrrhs** [comment]
@tianxia0079 进群沟通吧
